<a href="https://colab.research.google.com/github/chw8207/NLP-study/blob/main/%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95_%EB%B0%8F_%EC%84%A4%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/자연어처리공부/NLP-study

/content/drive/MyDrive/Colab Notebooks/자연어처리공부/NLP-study


In [ ]:
!git clone https://chw8207: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@github.com/chw8207/NLP-study.git

Cloning into 'NLP-study'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


In [ ]:
# 텐서플로우(tensorflow)
import tensorflow as tf

# 버전 확인
tf.__version__

'2.9.2'

In [ ]:
# 케라스(keras)
import keras

# 버전 확인
keras.__version__

'2.9.0'

In [ ]:
# 젠심(gensim)
# 토픽 모델링과 자연어처리를 수행할 수 있게 하는 라이브러리
# !pip install gensim
import gensim

# 버전 확인
gensim.__version__

'3.6.0'

In [ ]:
# NLTK와 NLTK Data 설치
import nltk

# 버전 확인
nltk.__version__

'3.7'

In [ ]:
#  NLTK Data 추가하기
nltk.download('book')

[nltk_data] Downloading collection 'book'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    

True

In [ ]:
# KoNLPy : 한국어 자연어처리를 위한 형태소 분석기
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 66.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 47.8 MB/s eta 0:00:00


In [ ]:
import konlpy

# 버전 확인
konlpy.__version__

'0.6.0'

In [1]:
# 넘파이
import numpy as np

In [ ]:
# 1차원 배열
vec = np.array([1,2,3,4,5])
print(vec)

[1 2 3 4 5]


In [ ]:
# 2차원 배열
mat = np.array([[10,20,30], [60,70,80]])
print(mat)

[[10 20 30]
 [60 70 80]]


In [ ]:
# 배열 타입 확인해보기
print('vec의 타입 :', type(vec))
print('mat의 타입 :', type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [ ]:
# 축 개수와 크기
print('vec의 축의 개수 :', vec.ndim)
print('vec의 크기: ', vec.shape)

vec의 축의 개수 : 1
vec의 크기:  (5,)


In [ ]:
print('mat의 축의 개수 :', mat.ndim)
print('mat의 크기: ', mat.shape)

mat의 축의 개수 : 2
mat의 크기:  (2, 3)


In [ ]:
# ndarray의 초기화
# 모든 값이 0인 2x3 배열 생성
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 모든 값이 1인 2x3 배열 생성
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 지정한 값으로 배열 생성
# 모든 값이 특정 상수일 경우
same_value_mat = np.full((2,3),7)
print(same_value_mat)

[[7 7 7]
 [7 7 7]]


In [ ]:
# 대각선으로는 1, 나머지는 0
# np.eye(행개수(행=열))
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# 임의의 값을 가지는 배열 생성하기
random_mat = np.random.random((2,3))
print(random_mat)

[[0.12626918 0.37659243 0.69969367]
 [0.73211361 0.86607959 0.43320868]]
