<a href="https://colab.research.google.com/github/chw8207/NLP-study/blob/main/%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95_%EB%B0%8F_%EC%84%A4%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/자연어처리공부/NLP-study

/content/drive/MyDrive/Colab Notebooks/자연어처리공부/NLP-study


In [ ]:
!git clone https://chw8207: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@github.com/chw8207/NLP-study.git

Cloning into 'NLP-study'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


In [ ]:
# 텐서플로우(tensorflow)
import tensorflow as tf

# 버전 확인
tf.__version__

'2.9.2'

In [ ]:
# 케라스(keras)
import keras

# 버전 확인
keras.__version__

'2.9.0'

In [ ]:
# 젠심(gensim)
# 토픽 모델링과 자연어처리를 수행할 수 있게 하는 라이브러리
# !pip install gensim
import gensim

# 버전 확인
gensim.__version__

'3.6.0'

In [ ]:
# NLTK와 NLTK Data 설치
import nltk

# 버전 확인
nltk.__version__

'3.7'

In [ ]:
#  NLTK Data 추가하기
nltk.download('book')

[nltk_data] Downloading collection 'book'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    

True

In [ ]:
# KoNLPy : 한국어 자연어처리를 위한 형태소 분석기
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 66.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 47.8 MB/s eta 0:00:00


In [ ]:
import konlpy

# 버전 확인
konlpy.__version__

'0.6.0'

### 넘파이(Numpy)

In [1]:
# 넘파이
import numpy as np

In [ ]:
# 1차원 배열
vec = np.array([1,2,3,4,5])
print(vec)

[1 2 3 4 5]


In [ ]:
# 2차원 배열
mat = np.array([[10,20,30], [60,70,80]])
print(mat)

[[10 20 30]
 [60 70 80]]


In [ ]:
# 배열 타입 확인해보기
print('vec의 타입 :', type(vec))
print('mat의 타입 :', type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [ ]:
# 축 개수와 크기
print('vec의 축의 개수 :', vec.ndim)
print('vec의 크기: ', vec.shape)

vec의 축의 개수 : 1
vec의 크기:  (5,)


In [ ]:
print('mat의 축의 개수 :', mat.ndim)
print('mat의 크기: ', mat.shape)

mat의 축의 개수 : 2
mat의 크기:  (2, 3)


In [ ]:
# ndarray의 초기화
# 모든 값이 0인 2x3 배열 생성
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 모든 값이 1인 2x3 배열 생성
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 지정한 값으로 배열 생성
# 모든 값이 특정 상수일 경우
same_value_mat = np.full((2,3),7)
print(same_value_mat)

[[7 7 7]
 [7 7 7]]


In [ ]:
# 대각선으로는 1, 나머지는 0
# np.eye(행개수(행=열))
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 임의의 값을 가지는 배열 생성하기
random_mat = np.random.random((2,3))
print(random_mat)

[[0.12626918 0.37659243 0.69969367]
 [0.73211361 0.86607959 0.43320868]]


In [ ]:
# 0부터 n-1까지의 값을 가지는 배열 생성
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# i부터 j-1까지 k씩 증가하는 배열 생성
range_n_step_vec = np.arange(1,10,2)
print(range_n_step_vec)

[1 3 5 7 9]


In [ ]:
# np.reshape()
# 내부 데이터는 변경하지 않으면서 구조를 바꿈
reshape_mat = np.array((np.arange(30)).reshape((5,6)))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 첫번째 행 출력하기
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [ ]:
# 두 번째 열 출력하기
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


In [2]:
# 넘파이 정수 인덱싱
mat = np.array([[1,2],[4,5],[7,8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [3]:
# 1행 0열의 원소 갖고오기
print(mat[1,0])

4


In [5]:
# mat[[2행, 1행],[0열, 1열]]
# 각 행과 열의 쌍을 매칭하면 2행 0열, 1행 1열의 두 개의 원소.
indexing_mat = mat[[2,1],[0,1]]
print(indexing_mat)

[7 5]


In [6]:
# 넘파이 연산
x = np.array([1,2,3])
y = np.array([4,5,6])

In [7]:
# 덧셈1
result1 = x+y
print(result1)

[5 7 9]


In [8]:
# 덧셈2
result2 = np.add(x,y)
print(result2)

[5 7 9]


In [9]:
# 뺄셈1
result1 = x-y
print(result1)

[-3 -3 -3]


In [11]:
# 뺄셈2
result2 = np.subtract(x,y)
print(result2)

[-3 -3 -3]


In [12]:
# 곱셈1
result3 = result2*x
print(result3)

[-3 -6 -9]


In [13]:
# 곱셈2
result4 = np.multiply(result2,x)
print(result4)

[-3 -6 -9]


In [14]:
# 나눗셈1
result5 = result4/x
print(result5)

[-3. -3. -3.]


In [15]:
# 나눗셈2
result6 = np.divide(result4,x)
print(result6)

[-3. -3. -3.]


In [17]:
# 벡터와 행렬곱 또는 행렬곱을 할 때
# dot()을 사용
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]


### 판다스 프로파일링

In [19]:
# 패키지 설치
!pip install -U pandas-profiling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.7/328.7 KB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 KB 9.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 KB 42.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 91.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 77.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 KB 33.8 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=1016710bdf86a46a5703e313508b3607e6c5f97e6e91f71cd50f4792b771ff92
  Stored in directory: /root/.cache/pip/wheels/23/14/6e/4be5bfeeb027f4939a01764b48edd5996acf574b0913fe5243
Successfully built htmlmin
  Attempting uninstall: typeguard
    Found existing installation: typeguard 2.7.1
    Unin

In [22]:
# 실습파일 불러오기
import pandas as pd
import pandas_profiling

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/자연어처리공부/NLP-study/NLP-study/data/spam.csv', encoding='latin1')

In [23]:
# 데이터 확인
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [24]:
# 프로파일링 결과 리포트를 pr에 저장하기
pr = data.profile_report()

In [25]:
# pr_report.html 파일로 저장
pr.to_file('./pr_report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]